### ISSUE TITLE
Unable to get Flamenco manager running.

### ISSUE THREAD

**Issue by chrisw31** [armadillica/flamenco-manager#6]
Hi,

I'm running Ubuntu 16.04 systems, a desktop and server. For some reason
I can't get the manage running, am I missing some packages on my system
maybe? I've added firewall rules to for the ports as well, it didn't
help. I get the output attached in the terminal. I've Googled as well,
can't find anyone with this problem.

Any help would be appreciated.

Thanks.
Chris.

[Flamenco manager error.txt](https://github.com/armadillica/flamenco-manager/files/1400889/Flamenco.manager.error.txt)

**Comment by djiamnot** [comment]
I am having the same issue on 2 different computers. However, the flamenco-manager 2.0.16-dev build that I found in another issue, does not seem to have this error.

**Comment by sybrenstuvel** [comment]
I'll release that version next week then. Until then you should be able to use that build you found.
